# Generated by Django 3.0.3 on 2020-02-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', height_field=40, upload_to='gallery', width_field=40),
        ),
    ]
