# Generated by Django 3.0.3 on 2020-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200218_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='gallery'),
        ),
    ]
